### ISSUE TITLE
Invalid actions?

### ISSUE THREAD

**Issue by huttarichard** [ericgjackson/slumbot2019#28]
So I just recently played againts slumbot and I want to ask if I encountered bug or Im just confused.

State I encountered was following `b200b2179b4200`

So me being BB, slumbot SB

SB - 50 and BB 100
SB is first to act. So slumbot raises to 200 which make sense, so he is adding 150 to pot.
Then Im raising by 2079, since Im 100 as BB in pot commited already final bet is 2179.

But then slumbut adding to po 4000. I added 2079 (previous bet), and by standart poker rules, opponent must raise at least double of previous bet which would tell me min raise here is 4158 (+ 200 of first raise slumbot made) = 4358?

Do I miss something?

**Comment by ericgjackson** [comment]
This stuff can get confusing.  To keep things clear in my mind, I like to think of the bet amounts as "bet to" amounts.  "b200" means the small blind has put a total of 200 chips into the pot preflop.  You can also describe this as a raise of 100 chips.  The big blind has put 100 into the pot (the blind) and the small blind is putting in an additional 100 chips.

Looking at the big blind's raise, it says he has put 2179 chips into the pot.  That is a raise of 1979 chips.  He has put 1979 additional chips into the pot over and above the 200 chips the small blind has put in.

Finally, the small blind's reraise is to 4200.  This represents a raise of 2021 chips (4200 - 2179).  Since 2021 > 1979, this is a valid raise.

Hope that helps.

**Comment by huttarichard** [comment]
oh you right, never mind, I was confused.
